//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectADONet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Бетоны
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Бетоны()
        {
            this.КолоннБет = new HashSet<КолоннБет>();
            this.ПерекрБет = new HashSet<ПерекрБет>();
            this.ПерехБет = new HashSet<ПерехБет>();
            this.СтеныБет = new HashSet<СтеныБет>();
        }
    
        public int IDБетона { get; set; }
        public string Класс { get; set; }
        public string Марка { get; set; }
        public Nullable<decimal> ПрочностьМпа { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<КолоннБет> КолоннБет { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПерекрБет> ПерекрБет { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПерехБет> ПерехБет { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СтеныБет> СтеныБет { get; set; }
    }
}
