//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectADONet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Колонны
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Колонны()
        {
            this.КолоннБет = new HashSet<КолоннБет>();
            this.КолоннЭтСек1 = new HashSet<КолоннЭтСек1>();
            this.КолоннЭтСек2 = new HashSet<КолоннЭтСек2>();
        }
    
        public int IDколонны { get; set; }
        public string Наименование { get; set; }
        public Nullable<decimal> ДлинаВСечении { get; set; }
        public Nullable<decimal> ШиринаВСечении { get; set; }
        public string ЛистПроекта { get; set; }
        public Nullable<int> IDПроекта { get; set; }
        public byte[] Изображение { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<КолоннБет> КолоннБет { get; set; }
        public virtual Проекты Проекты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<КолоннЭтСек1> КолоннЭтСек1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<КолоннЭтСек2> КолоннЭтСек2 { get; set; }

        //чтобы в выпадающем меню отражались названия колонн, нужно переопределить метод ToString()
        public override string ToString()
        {
            return Наименование; // возвращает название колонны
        }
    }
}
