//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectADONet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Перекрытия
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Перекрытия()
        {
            this.ПерекрБет = new HashSet<ПерекрБет>();
            this.ПерекрЭтСек1 = new HashSet<ПерекрЭтСек1>();
            this.ПерекрЭтСек2 = new HashSet<ПерекрЭтСек2>();
        }
    
        public int IDПерекрытия { get; set; }
        public string Наименование { get; set; }
        public Nullable<decimal> Объем { get; set; }
        public Nullable<decimal> Толщина { get; set; }
        public string ЛистПроекта { get; set; }
        public Nullable<int> IDПроекта { get; set; }
        public byte[] Изображение { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПерекрБет> ПерекрБет { get; set; }
        public virtual Проекты Проекты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПерекрЭтСек1> ПерекрЭтСек1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПерекрЭтСек2> ПерекрЭтСек2 { get; set; }

        //чтобы в выпадающем меню отражались названия перекрытий, нужно переопределить метод ToString()
        public override string ToString()
        {
            return Наименование; // возвращает название перекрытия
        }
    }
}
