//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectADONet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Секции
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Секции()
        {
            this.ЭтажиСек1 = new HashSet<ЭтажиСек1>();
            this.ЭтажиСек2 = new HashSet<ЭтажиСек2>();
        }
    
        public int IDСекции { get; set; }
        public string НаименованиеСекции { get; set; }
        public string ОсиРасположения { get; set; }
        public Nullable<decimal> ОтноситОтметкаНиза0ЭтажаСек { get; set; }
        public Nullable<decimal> АбсолютОтметкаНуля { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭтажиСек1> ЭтажиСек1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭтажиСек2> ЭтажиСек2 { get; set; }

        //чтобы в выпадающем меню отражались названия секций, нужно переопределить метод ToString()
        public override string ToString()
        {
            return НаименованиеСекции; // возвращает название стены
        }
    }
}
