//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectADONet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Стены
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Стены()
        {
            this.СтеныБет = new HashSet<СтеныБет>();
            this.СтеныЭтСек1 = new HashSet<СтеныЭтСек1>();
            this.СтеныЭтСек2 = new HashSet<СтеныЭтСек2>();
        }
    
        public int IDСтены { get; set; }
        public string Наименование { get; set; }
        public Nullable<decimal> Объем { get; set; }
        public string ЛистПроекта { get; set; }
        public Nullable<int> IDПроекта { get; set; }
        public byte[] Изображение { get; set; }
    
        public virtual Проекты Проекты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СтеныБет> СтеныБет { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СтеныЭтСек1> СтеныЭтСек1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СтеныЭтСек2> СтеныЭтСек2 { get; set; }

        //чтобы в выпадающем меню отражались названия стен, нужно переопределить метод ToString()
        public override string ToString()
        {
            return Наименование; // возвращает название стены
        }
    }
}
