//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectADONet
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЭтажиСек2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ЭтажиСек2()
        {
            this.КолоннЭтСек2 = new HashSet<КолоннЭтСек2>();
            this.ПерекрЭтСек2 = new HashSet<ПерекрЭтСек2>();
            this.ПерехЭтСек2 = new HashSet<ПерехЭтСек2>();
            this.СтеныЭтСек2 = new HashSet<СтеныЭтСек2>();
        }
    
        public int IDЭтажаСек2 { get; set; }
        public Nullable<int> НомерЭтажаСек { get; set; }
        public Nullable<int> НомерЯрусаСек { get; set; }
        public Nullable<decimal> ВысотаЭтажаСек { get; set; }
        public Nullable<decimal> ВысотаСтенКолонн { get; set; }
        public Nullable<decimal> ТолщПерекрытия { get; set; }
        public Nullable<int> IDСекции { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<КолоннЭтСек2> КолоннЭтСек2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПерекрЭтСек2> ПерекрЭтСек2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПерехЭтСек2> ПерехЭтСек2 { get; set; }
        public virtual Секции Секции { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СтеныЭтСек2> СтеныЭтСек2 { get; set; }

        //чтобы в выпадающем меню отражались названия этажей, нужно переопределить метод ToString()
        public override string ToString()
        {
            return $"Этаж {НомерЭтажаСек}"; // возвращает номер этажа
        }
    }
}
