//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectADONet
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЭтажиСек1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ЭтажиСек1()
        {
            this.КолоннЭтСек1 = new HashSet<КолоннЭтСек1>();
            this.ПерекрЭтСек1 = new HashSet<ПерекрЭтСек1>();
            this.ПерехЭтСек1 = new HashSet<ПерехЭтСек1>();
            this.СтеныЭтСек1 = new HashSet<СтеныЭтСек1>();
        }
    
        public int IDЭтажаСек1 { get; set; }
        public Nullable<int> НомерЭтажаСек { get; set; }
        public Nullable<int> НомерЯрусаСек { get; set; }
        public Nullable<decimal> ВысотаЭтажаСек { get; set; }
        public Nullable<decimal> ВысотаСтенКолонн { get; set; }
        public Nullable<decimal> ТолщПерекрытия { get; set; }
        public Nullable<int> IDСекции { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<КолоннЭтСек1> КолоннЭтСек1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПерекрЭтСек1> ПерекрЭтСек1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПерехЭтСек1> ПерехЭтСек1 { get; set; }
        public virtual Секции Секции { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СтеныЭтСек1> СтеныЭтСек1 { get; set; }

        //чтобы в выпадающем меню отражались названия этажей, нужно переопределить метод ToString()
        public override string ToString()
        {
            return $"Этаж {НомерЭтажаСек}"; // возвращает номер этажа
        }
    }
}
